# Generated by Django 4.2.4 on 2023-08-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowering',
            name='category',
            field=models.CharField(choices=[('in', 'indoorplants'), ('fl', 'flowering'), ('se', 'season'), ('fe', 'foliage')], default='default_category', max_length=100),
        ),
        migrations.AddField(
            model_name='foliage',
            name='category',
            field=models.CharField(choices=[('in', 'indoorplants'), ('fl', 'flowering'), ('se', 'season'), ('fe', 'foliage')], default='default_category', max_length=100),
        ),
        migrations.AddField(
            model_name='indoorplants',
            name='category',
            field=models.CharField(choices=[('in', 'indoorplants'), ('fl', 'flowering'), ('se', 'season'), ('fe', 'foliage')], default='default_category', max_length=100),
        ),
        migrations.AddField(
            model_name='season',
            name='category',
            field=models.CharField(choices=[('in', 'indoorplants'), ('fl', 'flowering'), ('se', 'season'), ('fe', 'foliage')], default='default_category', max_length=100),
        ),
    ]
