# Generated by Django 4.2.4 on 2023-08-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_flowering_category_foliage_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flowering',
        ),
        migrations.DeleteModel(
            name='foliage',
        ),
        migrations.DeleteModel(
            name='indoorplants',
        ),
        migrations.DeleteModel(
            name='season',
        ),
    ]
