# Generated by Django 4.2.4 on 2023-09-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
